### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by GHOSTANDBREAD** [RichardSunnyMeng/LatentWatermark-official-codes#2]
Hello, author. Thank you for your excellent work. I encountered the following issue while trying to reproduce it. 

> Traceback (most recent call last):
  File "./training_stage1.py", line 127, in <module>
    train_pipeline(args, cfg)
  File "./training_stage1.py", line 29, in train_pipeline
    message_model = ModelWarper("message_model", cfg["message_model"], logger)
  File "/hy-tmp/LatentWatermark-official-codes-main/models/__init__.py", line 20, in __init__
    self.model = NaiveMessageModel(**config['model']['kwargs']).to(device=self.device)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 987, in to
    return self._apply(convert)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 662, in _apply
    param_applied = fn(param)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

I am using an A10 GPU. Is there any requirement regarding the type of GPU used? 
Thank you very much if you can answer the question.

**Comment by jinganglang567** [comment]
@GHOSTANDBREAD hello ,nice to meet you, i am interesting in the work too, can you help offer the dataset LAION5+,i didn't find in the web

**Comment by RichardSunnyMeng** [comment]
> Hello, author. Thank you for your excellent work. I encountered the following issue while trying to reproduce it.
> 
> > Traceback (most recent call last):
> > File "./training_stage1.py", line 127, in 
> > train_pipeline(args, cfg)
> > File "./training_stage1.py", line 29, in train_pipeline
> > message_model = ModelWarper("message_model", cfg["message_model"], logger)
> > File "/hy-tmp/LatentWatermark-official-codes-main/models/**init**.py", line 20, in **init**
> > self.model = NaiveMessageModel(**config['model']['kwargs']).to(device=self.device)
> > File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 987, in to
> > return self._apply(convert)
> > File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
> > module._apply(fn)
> > File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
> > module._apply(fn)
> > File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 662, in _apply
> > param_applied = fn(param)
> > File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 985, in convert
> > return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
> > File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/cuda/**init**.py", line 229, in _lazy_init
> > torch._C._cuda_init()
> > RuntimeError: No CUDA GPUs are available
> 
> I am using an A10 GPU. Is there any requirement regarding the type of GPU used? Thank you very much if you can answer the question.

Do you input your Cuda device when you run the shell script?

**Comment by RichardSunnyMeng** [comment]
> @GHOSTANDBREAD hello ,nice to meet you, i am interesting in the work too, can you help offer the dataset LAION5+,i didn't find in the web

You can refer to https://github.com/open-mmlab/PowerPaint/issues/87. Other images are also OK, I think.

**Comment by GHOSTANDBREAD** [comment]
Thank you very much for your answer
