### ISSUE TITLE
about the cuda memory

### ISSUE THREAD

**Issue by jinganglang567** [RichardSunnyMeng/LatentWatermark-official-codes#3]
sorry to bother you, doctor, i am interesting in your work,but i have a problem about the cuda memory,when i run the train_stage_3.py. my cuda is out of memeory, so i want to know how to run this command in four gpus.And four 1080ti is enough?

**Comment by RichardSunnyMeng** [comment]
Maybe it cannot run easily on multiple gpus because the batch size is already small..... I run it on one 32GB gpu.

**Comment by lifeofstudy** [comment]
> sorry to bother you, doctor, i am interesting in your work,but i have a problem about the cuda memory,when i run the train_stage_3.py. my cuda is out of memeory, so i want to know how to run this command in four gpus.And four 1080ti is enough?

Hello, could you please provide the configuration of your reproducible environment, including the torch version, python version, cuda version, etc. I have always encountered various version problems when reproducing. Can you provide a detailed requirements.txt? Thank you.
